### ISSUE TITLE
Loading sample buckets seems to silently fail on enterprise analytics

### ISSUE THREAD

**Issue by Couch-Matt** [couchbaselabs/cbdinocluster#114]
Using the following yaml:
```
columnar: true
nodes:
  - count: 3
    version: 1.2.0-1154
docker:
  dns: true
```
When using this command:
```
./cbdinocluster-linux-arm64 buckets load-sample 9c9fa894-e727-4dc3-8eeb-f5d3b5aae421 travel-sample
```
I am seeing the expected output and not getting returned an error, but when trying to use the travel sample in tests I am seeing failures because it doesn't exist. This appars to be a regression and didn't happen with my previous version of Cbdyn (v0.0.65 i believe) and I was able to run those tests with no issue. I see this locally and on Jenkins with 0.0.73
